### ISSUE TITLE
ReferenceError: atob is not defined

### ISSUE THREAD

**Issue by Krylanc3lo** [pavlodvornikov/aiocfscrape#15]
Hello,

I got the below error since  a couple of days: **js2py.internals.simplex.JsException: ReferenceError: atob is not defined**

File "/home/maxx/.local/lib/python3.6/site-packages/js2py/base.py", line 1074, in get
    return self.prototype.get(prop, throw)
  File "/home/maxx/.local/lib/python3.6/site-packages/js2py/base.py", line 1079, in get
    raise MakeError('ReferenceError', '%s is not defined' % prop)
js2py.internals.simplex.JsException: ReferenceError: atob is not defined

Anyone is experiencing the same ?

Thank you!

**Comment by thanh109** [comment]
same me

**Comment by Krylanc3lo** [comment]
Hello,

issue has been fixed by @VeNoMouS here: https://github.com/Anorov/cloudflare-scrape/issues/215
