### ISSUE TITLE
Project Takeover Request

### ISSUE THREAD

**Issue by Nachtalb** [pavlodvornikov/aiocfscrape#19]
Are you still working on this project? If not I would like to take it over and maintain it. I have use for this package and have already updated the code locally to make it work again with my program. 

I thought about just making a PR but you haven't done anything in a year and you also seem to be not doing anything else: 
![image](https://user-images.githubusercontent.com/9467802/77215701-f52be000-6b15-11ea-8640-b3332988d9b5.png)

If possible I would like to take over the pip repo. If you don't want me to take over the project I would gladly make a PR, though I don't know how much sense that makes because you don't seem to be really active on Github (for the future of this project). In the case that you don't answer to this request within a week, I will create a `aiocfscrape2` package on pip and will continue updating and maintaining it as that. 

CC:  #17, #16, #10, #8, #1

**Comment by pavlodvornikov** [comment]
I don't have any use for this project anymore, thats why I wasn't updating it since last year. So I would gladly add you to the maintainers of the GitHub repo as well as PyPi repo. Let me know your username on PyPi.

**Comment by Nachtalb** [comment]
Thanks for opportunity! My PyPi name is `nicke`. >> https://pypi.org/user/nicke/
