### ISSUE TITLE
Is js2py enough secure?

### ISSUE THREAD

**Issue by enomado** [pavlodvornikov/aiocfscrape#23]
I have been using cloudflare-scrape and it is using node for js inperpretation. It was using js2py in past.

So I found a comment - https://github.com/Anorov/cloudflare-scrape/pull/278#issuecomment-520240606

**Comment by Nachtalb** [comment]
I am working on updating the package to the latest version of `cfscrape` which will replace `js2py` with `nodejs`.

**Comment by Nachtalb** [comment]
See: https://github.com/pavlodvornikov/aiocfscrape/tree/na/update-to-latest-cfscrape

**Comment by Nachtalb** [comment]
I'll close this in favour of #27. We will need to rewrite this package.
