### ISSUE TITLE
'URL' object has no attribute 'decode'

### ISSUE THREAD

**Issue by ItsASmallWorld** [pavlodvornikov/aiocfscrape#24]
aiocfscrape==1.0.0
aiohttp==3.6.2 

 File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiocfscrape/__init__.py", line 87, in _request
    return await self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aiocfscrape/__init__.py", line 125, in solve_cf_challenge
    parsed_url = urlparse(resp.url)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 367, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 123, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 107, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 107, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'URL' object has no attribute 'decode'

**Comment by pystar1007** [comment]
same issue to me.
Please fix this.

**Comment by DevL0rd** [comment]
It's possible it is the version of aiohttp we are using.
I'm going to be looking into it now, and will make a PR when I figure out what is going on

**Comment by DevL0rd** [comment]
@ItsASmallWorld @pystar1007 I pushed a fix. Lets hope it gets accepted :)
It did have to do with the version of aiohttp. They changed the data struct of the response object. and it didn't like not having org_method undefined before checking if it is None.

**Comment by DevL0rd** [comment]
Ok so this module is too outdated from the original cfscrape.
I pulled a fresh source of cfscrape and started making it IO again.
It will be completely working tommorrow.
https://github.com/DevL0rd/aio-cloudflare-scrape

**Comment by aadibajpai** [comment]
> @ItsASmallWorld @pystar1007 I pushed a fix. Lets hope it gets accepted :)
> It did have to do with the version of aiohttp. They changed the data struct of the response object. and it didn't like not having org_method undefined before checking if it is None.

Same issue, does it work now?

also, @flabbet see this

**Comment by aadibajpai** [comment]
> Ok so this module is too outdated from the original cfscrape.
> I pulled a fresh source of cfscrape and started making it IO again.
> It will be completely working tommorrow.
> https://github.com/DevL0rd/aio-cloudflare-scrape

does this work, @DevL0rd?

**Comment by andress134** [comment]
> > Ok so this module is too outdated from the original cfscrape.
> > I pulled a fresh source of cfscrape and started making it IO again.
> > It will be completely working tommorrow.
> > https://github.com/DevL0rd/aio-cloudflare-scrape
> 
> does this work, @DevL0rd?

cloudflare has updated new challenge this lib dont work for new challenge

**Comment by andress134** [comment]
> Ok so this module is too outdated from the original cfscrape.
> I pulled a fresh source of cfscrape and started making it IO again.
> It will be completely working tommorrow.
> https://github.com/DevL0rd/aio-cloudflare-scrape

cloudflare has updated new challenge this lib dont work for new challenge

**Comment by Nachtalb** [comment]
This will be fixed with https://github.com/pavlodvornikov/aiocfscrape/tree/na/update-to-latest-cfscrape and as I explained some stuff in [here](https://github.com/pavlodvornikov/aiocfscrape/issues/21#issuecomment-722399247), an issue which also talks about this error, I'll close this one
