### ISSUE TITLE
If host does not return a "Server" header, an exception occurs

### ISSUE THREAD

**Issue by dteh** [pavlodvornikov/aiocfscrape#7]
If the host does not return a Server header, the value is None, the default case should be a string.
```
File "/usr/lib/python3.6/site-packages/aiocfscrape/__init__.py", line 39, in _request
    elif resp.status == 403 and resp.headers.get("Server").startswith("cloudflare") and not allow_403:
AttributeError: 'NoneType' object has no attribute 'startswith'
```
I think ` resp.headers.get("Server")` should be ` resp.headers.get("Server", "")`

**Comment by pavlodvornikov** [comment]
@dteh yes, you are right. Default value also must be added at line [35](https://github.com/pavlodvornikov/aiocfscrape/blob/master/aiocfscrape/__init__.py#L35)

Would you mind adding PR for this ?

**Comment by pavlodvornikov** [comment]
pr #9

**Comment by gaardiolor** [comment]
@pavlodvornikov this fix is not in the latest version of the pypi package (0.0.6), can you maybe publish a new version ? thanks!

**Comment by pavlodvornikov** [comment]
@gaardiolor updated, thanks for pointing that out
